# Generated by Django 4.0.6 on 2022-07-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_tes2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tes',
        ),
        migrations.DeleteModel(
            name='Tes2',
        ),
    ]
