# Generated by Django 4.0.6 on 2022-07-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_answer_teste'),
        ('notas', '0004_delete_tes_delete_tes2'),
    ]

    operations = [
    ]
