# Generated by Django 4.0.6 on 2022-07-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_merge_0002_answer_teste_0004_delete_tes_delete_tes2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
